<?php $_code=$this->getMethodCode() ?>
<input type="hidden" name="<?php echo $_code ?>_cc_type" />
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <?php if((boolean)Mage::getStoreConfig('payment/fatzebra/show_logo')): ?>
        <a href="https://www.fatzebra.com.au/?rel=logo" title="Fat Zebra Certified" style="float: right;"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/payments/Fat-Zebra-Certified-small.png"; ?>" alt="Fat Zebra Certified" border="0" /></a>
    <?php endif; ?>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner"><?php echo Mage::helper('payment')->__('Name on Card') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Name on Card') ?>" class="required-entry input-text" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->getInfoData('cc_owner') ?>"/>
        </div>
    </li>
    <input type="hidden" name="payment[cc_type]" id="<?php echo $_code ?>_cc_type" />
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
            <?php foreach($this->getCcAvailableTypes() as $typeCode => $typeName): ?>
                <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . "/payments/" . $typeCode . ".png"; ?>" alt="<?php echo $typeName; ?>" class="card-logo" id="card-<?php echo strtolower($typeCode); ?>" style="margin-top: -5px; opacity: 0.5;" />
            <?php endforeach; ?>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
            <?php foreach ($this->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
            <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>"/>
        </div>
    </li>
    <?php endif; ?>
</ul>

<script type="text/javascript">
    $("fatzebra_cc_number").observe("keyup", function() {
        var value = $("fatzebra_cc_number").value;
        if(value.length === 0) return;

        var card_id, code;
        if(value.match(/^4/)) {
            card_id = "card-vi";
            code = "VI";
        }
        if(value.match(/^5/)) {
            card_id = "card-mc";
            code = "MC";
        }
        if(value.match(/^(34|37)/)) {
            card_id = "card-ae";
            code = "AE";
        }
        if(value.match(/^(36)/)) {
            card_id = "card-dic";
            code = "DIC";
        }
        if(value.match(/^(35)/)) {
            card_id = "card-jcb";
            code = "JCB";
        }
        if(value.match(/^(65)/)) {
            card_id = "card-di";
            code = "DI";
        }

        $$("img.card-logo").each(function(x) {
            if(x.id != card_id) {
                $(x).setStyle({opacity: 0.5});
            } else {
                $(x).setStyle({opacity: 1.0});
            }
        });

        $("fatzebra_cc_type").value = code;

    });
</script>
